# --- Vaihe 1: Build ---
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- Vaihe 2: Production ---
FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

# Kopioidaan vain backend ja buildattu frontend
COPY src/services ./src/services
COPY --from=build /app/dist ./dist

ENV NODE_ENV=production
ENV PORT=3001
EXPOSE 3001

CMD ["node", "src/services/server.js"]
