version: "3.9"
services:
  soppela_web:
    build: .
    container_name: soppela_web
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - soppela_net

networks:
  soppela_net:
    driver: bridge
